Don't call `bazel info` in `bazel` wrapper script (#1074)
Summary: We were seeing `ci/bazel_build_deps.sh` fail on many peoples
diffs. The failure was a strange looking bazel fatal error seemingly
related to [this bazel
bug](https://github.com/bazelbuild/bazel/issues/15079). We were seeing
very similar errors (see below). I made a minimal repro for the bazel
team to look at
[here](https://github.com/JamesMBartlett/bazel_fatal_repro). It seems
like there's some issue with bazel when `bazel info execution_root` is
called in between two cquery calls. Our bazel wrapper script currently
calls `bazel info execution_root` to work out if bazel is being called
on the pixie repo. We can instead check the `WORKSPACE` file to see if
this is the pixie repo.

Also fix the `grep` to avoid errors if the cquery returns no targets.

Type of change: /kind test-infra

Test Plan: I tested using the changes in #1039 which trigger this fatal
error in `ci/bazel_build_deps.sh`

<details>
<summary>error message</summary>
<blockquote>
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: query-requested node
'ConfiguredTargetKey{label=//src:stitcher_test,
config=BuildConfigurationKey[3f007b0057ace6778698ecbef2f9313f699b644d422159091251c0d3c8629502]}'
was unavailable in the query environment graph. If you come across this
error, please add to https://github.com/bazelbuild/bazel/issues/15079 or
contact the bazel configurability team.
at
com.google.common.base.Preconditions.checkState(Preconditions.java:590)
at
com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:435)
at
com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:484)
at
com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:303)
at
com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:103)
at
com.google.devtools.build.lib.query2.engine.AllRdepsFunction.lambda$eval$0(AllRdepsFunction.java:99)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.lambda$eval$0(AbstractBlazeQueryEnvironment.java:255)
at
com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:196)
at
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
at
com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at
com.google.common.util.concurrent.CombinedFuture$CombinedFutureInterruptibleTask.execute(CombinedFuture.java:108)
at
com.google.common.util.concurrent.CombinedFuture.handleAllCompleted(CombinedFuture.java:65)
at
com.google.common.util.concurrent.AggregateFuture.processCompleted(AggregateFuture.java:301)
at
com.google.common.util.concurrent.AggregateFuture.decrementCountAndMaybeComplete(AggregateFuture.java:283)
at
com.google.common.util.concurrent.AggregateFuture.lambda$init$0(AggregateFuture.java:157)
at
com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at
com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
at
com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
at
com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:136)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractBlazeQueryEnvironment.java:499)
at
com.google.common.util.concurrent.AggregateFuture.init(AggregateFuture.java:140)
at
com.google.common.util.concurrent.CombinedFuture.<init>(CombinedFuture.java:55)
at
com.google.common.util.concurrent.Futures$FutureCombiner.call(Futures.java:745)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.whenAllSucceedCall(AbstractBlazeQueryEnvironment.java:291)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.whenSucceedsCall(AbstractBlazeQueryEnvironment.java:279)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.eval(AbstractBlazeQueryEnvironment.java:252)
at
com.google.devtools.build.lib.query2.engine.AllRdepsFunction.eval(AllRdepsFunction.java:84)
at
com.google.devtools.build.lib.query2.engine.RdepsFunction.lambda$evalWithBoundedDepth$1(RdepsFunction.java:126)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.lambda$transformAsync$1(AbstractBlazeQueryEnvironment.java:300)
at
com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
at
com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)
at
com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
at
com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at
com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
at
com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
at
com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:136)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractBlazeQueryEnvironment.java:499)
at
com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:43)
at
com.google.common.util.concurrent.Futures.transformAsync(Futures.java:456)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.transformAsync(AbstractBlazeQueryEnvironment.java:298)
at
com.google.devtools.build.lib.query2.engine.RdepsFunction.evalWithBoundedDepth(RdepsFunction.java:128)
at
com.google.devtools.build.lib.query2.engine.RdepsFunction.eval(RdepsFunction.java:74)
at
com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.eval(AbstractBlazeQueryEnvironment.java:251)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:128)
at
com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evaluateQueryInternal(AbstractBlazeQueryEnvironment.java:172)
at
com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.evaluateQuery(PostAnalysisQueryEnvironment.java:154)
at
com.google.devtools.build.lib.buildtool.PostAnalysisQueryProcessor.doPostAnalysisQuery(PostAnalysisQueryProcessor.java:198)
at
com.google.devtools.build.lib.buildtool.PostAnalysisQueryProcessor.process(PostAnalysisQueryProcessor.java:88)
at
com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:213)
at
com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:494)
at
com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:462)
at
com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:183)
at
com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:608)
at
com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:233)
at
com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
at
com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:566)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown
Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)

</blockquote>
</details>

---------

Signed-off-by: James Bartlett <jamesbartlett@pixielabs.ai>
Signed-off-by: Vihang Mehta <vihang@pixielabs.ai>
Co-authored-by: Vihang Mehta <vihang@pixielabs.ai>